[build]
  command = "pnpm build"
  publish = "dist/public"
  functions = "dist/server"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify/:splat"
  status = 200 